name: Python CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Allow one of the matrix builds to fail without failing others
      matrix:
        os: [ubuntu-latest]
        
        
    # The job
    name: Python ${{ matrix.python-version }} / ${{ matrix.os }}
    
    # The steps in the job. Each step either RUNS code, or USES an action
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Run tests and linting
        run: |
          g++ knapsack.cpp
          ./a.out