name: Python CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Allow one of the matrix builds to fail without failing others
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        
        
    # The job
    name: Python ${{ matrix.python-version }} / ${{ matrix.os }}
    
    # The steps in the job. Each step either RUNS code, or USES an action
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      - name: Run tests and linting
        run: |
          sudo apt install python3-dev cmake --quiet
          pip install pybind11 invoke --upgrade
          python -m pybind11 --cmakedir
          git clone https://github.com/pybind/pybind11
          g++ knapsack.cpp
          ./a.out